apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
type: Opaque
data:
  RabbitMqHost: {{ .Values.RabbitMqHost | b64enc }}
  RabbitMqUsername: {{ .Values.RabbitMqUsername | b64enc }}
  RabbitMqPassword: {{ .Values.RabbitMqPassword | b64enc }}