# Declare variables to be passed into your templates.

replicaCount: 0
maxReplicaCount: 30

image:
  repository: my-consumer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.0.1

env:
  RabbitMq:
    Host: rabbitmq.dev.svc.cluster.local
    VirtualHost: /
    QueueName: MyConsumer.UserCreatedConsumer
  Serilog:
    Url: http://my-seq.dev.svc.cluster.local

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
